language: ruby
rvm:
    - 2.2
before_script:
    - gem install awesome_bot
script:
    - awesome_bot README.md --white-list CONTRIBUTING.md,https://www.threatcrowd.org/,https://intel.deepviz.com/recap_network.php,https://www.fireeye.com/services/freeware/ioc-editor.html